---
- name: Add certbot apt repo
  apt_repository:
    repo: ppa:certbot/certbot
    state: present

- name: Install certbot
  apt:
    pkg:
      - certbot
    update_cache: true
    state: present

- name: Ensure Let's Encrypt uses API v2
  lineinfile:
    path: /etc/letsencrypt/cli.ini
    regexp: '^server'
    line: 'server = https://acme-v02.api.letsencrypt.org/directory'

- name: Register certbot certificate file
  stat:
    path: "/etc/letsencrypt/live/{{ rest_backup_server }}/fullchain.pem"
  register: certbot_certificate_file_path

- name: Generate Certificates
  command: certbot certonly -d {{ rest_backup_server }} --agree-tos --email {{ letsencrypt_email }} --standalone
  when: not certbot_certificate_file_path.stat.exists

- name: enable (limited) http in ufw for certbot renewal
  ufw:
    rule: limit
    port: http

- name: ensure certbot renew in cron
  cron:
    name: "certbot renew weekly"
    special_time: weekly
    job: "certbot renew"
    user: root