---
- name: Ensure PHP nginx installed
  apt:
    name:
      - nginx
      - php7.2-fpm
      - php7.2

- name: Ensure current Dokuwiki
  unarchive: 
    src: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
    dest: /tmp
    remote_src: yes

- name: Ensure Dokuwiki directory exists
  file:
    path: /var/www/dokuwiki
    state: directory
    owner: www-data
    group: www-data

- name: Ensure dokuwiki install.php not present
  file:
    path: /var/www/dokuwiki/install.php
    state: absent

- name: Ensure Nginx Dokuwiki conf
  template:
    src: dokuwiki.nginx
    dest: "/etc/nginx/{{ nginx_domain_name }}.d/dokuwiki.conf"

 
